create table Customer_1(CUSTOMER NUMBER(4) PRIMARY KEY, FIRSTNAME VARCHAR2(30) NOT NULL, LASTNAME VARCHAR2(30) NOT NULL,
DOB DATE NOT NULL, GENDER VARCHAR2(7) NOT NULL, CITY VARCHAR2(50), COUNTRY VARCHAR2(25), EMAIL VARCHAR2(50),
ANNUAL_SALARY NUMBER(20,5) NOT NULL);

DROP TABLE Customer_1;

SELECT * FROM Customer_1;

CREATE SEQUENCE custSeq
MINVALUE 100
MAXVALUE 1000
START WITH 100
INCREMENT BY 1;

SELECT custSeq.nextval from dual;