create table Customer_4(CUSTOMERID NUMBER(4) PRIMARY KEY,
FIRSTNAME VARCHAR2(30) NOT NULL, LASTNAME VARCHAR2(30) NOT NULL,
CONTACT VARCHAR2(30) NOT NULL, GENDER VARCHAR2(7) NOT NULL, MARRIED VARCHAR2(20), CITY VARCHAR2(50) );

CREATE TABLE Hobby_4(CUSTOMERID NUMBER(4), HOBBY VARCHAR2(30), PRIMARY KEY(CUSTOMERID,HOBBY),
FOREIGN KEY(CUSTOMERID) REFERENCES Customer_4(CUSTOMERID));

INSERT INTO Customer_4 VALUES (100,'Veena','Jose','8456798546','Female','Yes','TVM');
INSERT INTO Customer_4 VALUES (101,'Vishal','Barad','8456798556','Male','Yes','AHD');

INSERT INTO Hobby_4 VALUES(100,'Cycling');
INSERT INTO Hobby_4 VALUES(100,'Cooking');
INSERT INTO Hobby_4 VALUES(101,'Cycling');
INSERT INTO Hobby_4 VALUES(101,'Driving');

select * from CUSTOMER_4;